# Voice-Only Omani Arabic Mental Health Chatbot
# Azure App Service Deployment Configuration

name: Deploy to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: omani-mental-health-bot
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.11'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 🔄 Checkout code
      uses: actions/checkout@v3
    
    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: 📦 Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: 🧪 Test system components
      run: |
        python -c "
        try:
            from config import settings
            print('✅ Configuration loaded successfully')
        except Exception as e:
            print(f'❌ Configuration error: {e}')
            exit(1)
        
        try:
            import whisper
            import azure.cognitiveservices.speech as speechsdk
            print('✅ Speech services available')
        except Exception as e:
            print(f'❌ Speech services error: {e}')
        
        try:
            from openai import OpenAI
            from anthropic import Anthropic
            print('✅ AI services available')
        except Exception as e:
            print(f'❌ AI services error: {e}')
        "
    
    - name: 🚀 Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    
    - name: ✅ Deployment complete
      run: |
        echo "🎉 Omani Mental Health Chatbot deployed successfully!"
        echo "🌐 Access at: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net" 